/**
 * CloudClaude Configuration Initialization Script
 * Interactive setup for first-time configuration
 */

import * as fs from 'fs/promises';
import * as path from 'path';
import * as readline from 'readline';

const CONFIG_DIR = path.join(process.cwd(), 'config');

interface CredentialsConfig {
    feishu: {
        appId: string;
        appSecret: string;
        encryptKey: string;
        verificationToken: string;
    };
    anthropic: {
        apiKey: string;
    };
}

async function question(rl: readline.Interface, prompt: string): Promise<string> {
    return new Promise((resolve) => {
        rl.question(prompt, (answer) => {
            resolve(answer);
        });
    });
}

async function main() {
    console.log('');
    console.log('╔═══════════════════════════════════════════╗');
    console.log('║       CloudClaude Configuration Setup      ║');
    console.log('╚═══════════════════════════════════════════╝');
    console.log('');

    const rl = readline.createInterface({
        input: process.stdin,
        output: process.stdout
    });

    try {
        // Check if credentials already exist
        const credentialsPath = path.join(CONFIG_DIR, 'credentials.json');
        let existingCredentials: CredentialsConfig | null = null;

        try {
            const content = await fs.readFile(credentialsPath, 'utf-8');
            existingCredentials = JSON.parse(content);
            console.log('⚠️  Existing configuration found.');
            const overwrite = await question(rl, 'Overwrite existing configuration? (y/N): ');
            if (overwrite.toLowerCase() !== 'y') {
                console.log('Configuration unchanged.');
                rl.close();
                return;
            }
        } catch {
            // No existing config
        }

        console.log('');
        console.log('📦 Feishu Configuration');
        console.log('   Get these from: https://open.feishu.cn/');
        console.log('');

        const feishuAppId = await question(rl, 'Feishu App ID: ');
        const feishuAppSecret = await question(rl, 'Feishu App Secret: ');
        const feishuEncryptKey = await question(rl, 'Feishu Encrypt Key (optional, press Enter to skip): ');
        const feishuVerificationToken = await question(rl, 'Feishu Verification Token (optional, press Enter to skip): ');

        console.log('');
        console.log('🤖 Anthropic Configuration');
        console.log('');

        const anthropicApiKey = await question(rl, 'Anthropic API Key: ');

        console.log('');
        console.log('💬 Default Chat Configuration');
        console.log('');

        const defaultChatId = await question(rl, 'Default Feishu Chat ID (optional, press Enter to skip): ');

        // Build credentials config
        const credentials: CredentialsConfig = {
            feishu: {
                appId: feishuAppId || 'cli_xxx',
                appSecret: feishuAppSecret || 'xxx',
                encryptKey: feishuEncryptKey || '',
                verificationToken: feishuVerificationToken || ''
            },
            anthropic: {
                apiKey: anthropicApiKey || 'sk-ant-xxx'
            }
        };

        // Ensure config directory exists
        await fs.mkdir(CONFIG_DIR, { recursive: true });

        // Save credentials
        await fs.writeFile(
            credentialsPath,
            JSON.stringify(credentials, null, 2)
        );

        // Create .env file
        const envContent = `# CloudClaude Environment Configuration
# Generated by init-config.ts

PORT=3000
NODE_ENV=development

# From credentials.json
ANTHROPIC_API_KEY=${credentials.anthropic.apiKey}

# Feishu
FEISHU_APP_ID=${credentials.feishu.appId}
FEISHU_APP_SECRET=${credentials.feishu.appSecret}

# Default Chat
DEFAULT_CHAT_ID=${defaultChatId || ''}

# Session Configuration
MAX_CONCURRENT_SESSIONS=3
SESSION_TIMEOUT_MS=3600000

# Logging
LOG_LEVEL=info
`;

        await fs.writeFile(path.join(process.cwd(), '.env'), envContent);

        // Ensure other config files exist
        const configFiles = [
            { name: 'tasks.json', content: { tasks: [] } },
            { name: 'sessions.json', content: { lastActive: null, sessions: [] } }
        ];

        for (const file of configFiles) {
            const filePath = path.join(CONFIG_DIR, file.name);
            try {
                await fs.access(filePath);
            } catch {
                await fs.writeFile(filePath, JSON.stringify(file.content, null, 2));
            }
        }

        // Create data directories
        await fs.mkdir(path.join(process.cwd(), 'data', 'sessions'), { recursive: true });
        await fs.mkdir(path.join(process.cwd(), 'logs'), { recursive: true });

        console.log('');
        console.log('✅ Configuration completed!');
        console.log('');
        console.log('Files created:');
        console.log('  • config/credentials.json');
        console.log('  • .env');
        console.log('  • config/tasks.json');
        console.log('  • config/sessions.json');
        console.log('  • data/sessions/');
        console.log('  • logs/');
        console.log('');
        console.log('Next steps:');
        console.log('  1. Configure Feishu webhook to point to:');
        console.log('     http://your-server:3000/webhook/feishu');
        console.log('  2. Start the server with: npm run dev');
        console.log('');

    } finally {
        rl.close();
    }
}

main().catch(console.error);
